# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/iaitech/DATA/programs/20221212

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/iaitech/DATA/programs/20221212

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/iaitech/DATA/programs/20221212/CMakeFiles /media/iaitech/DATA/programs/20221212//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/iaitech/DATA/programs/20221212/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VA

# Build rule for target.
VA: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VA
.PHONY : VA

# fast build rule for target.
VA/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/build
.PHONY : VA/fast

Display.o: Display.cpp.o
.PHONY : Display.o

# target to build an object file
Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Display.cpp.o
.PHONY : Display.cpp.o

Display.i: Display.cpp.i
.PHONY : Display.i

# target to preprocess a source file
Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Display.cpp.i
.PHONY : Display.cpp.i

Display.s: Display.cpp.s
.PHONY : Display.s

# target to generate assembly for a file
Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Display.cpp.s
.PHONY : Display.cpp.s

HungarianAlg.o: HungarianAlg.cpp.o
.PHONY : HungarianAlg.o

# target to build an object file
HungarianAlg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/HungarianAlg.cpp.o
.PHONY : HungarianAlg.cpp.o

HungarianAlg.i: HungarianAlg.cpp.i
.PHONY : HungarianAlg.i

# target to preprocess a source file
HungarianAlg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/HungarianAlg.cpp.i
.PHONY : HungarianAlg.cpp.i

HungarianAlg.s: HungarianAlg.cpp.s
.PHONY : HungarianAlg.s

# target to generate assembly for a file
HungarianAlg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/HungarianAlg.cpp.s
.PHONY : HungarianAlg.cpp.s

Intersection.o: Intersection.cpp.o
.PHONY : Intersection.o

# target to build an object file
Intersection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Intersection.cpp.o
.PHONY : Intersection.cpp.o

Intersection.i: Intersection.cpp.i
.PHONY : Intersection.i

# target to preprocess a source file
Intersection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Intersection.cpp.i
.PHONY : Intersection.cpp.i

Intersection.s: Intersection.cpp.s
.PHONY : Intersection.s

# target to generate assembly for a file
Intersection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Intersection.cpp.s
.PHONY : Intersection.cpp.s

Kalman.o: Kalman.cpp.o
.PHONY : Kalman.o

# target to build an object file
Kalman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Kalman.cpp.o
.PHONY : Kalman.cpp.o

Kalman.i: Kalman.cpp.i
.PHONY : Kalman.i

# target to preprocess a source file
Kalman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Kalman.cpp.i
.PHONY : Kalman.cpp.i

Kalman.s: Kalman.cpp.s
.PHONY : Kalman.s

# target to generate assembly for a file
Kalman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Kalman.cpp.s
.PHONY : Kalman.cpp.s

MultiCams.o: MultiCams.cpp.o
.PHONY : MultiCams.o

# target to build an object file
MultiCams.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/MultiCams.cpp.o
.PHONY : MultiCams.cpp.o

MultiCams.i: MultiCams.cpp.i
.PHONY : MultiCams.i

# target to preprocess a source file
MultiCams.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/MultiCams.cpp.i
.PHONY : MultiCams.cpp.i

MultiCams.s: MultiCams.cpp.s
.PHONY : MultiCams.s

# target to generate assembly for a file
MultiCams.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/MultiCams.cpp.s
.PHONY : MultiCams.cpp.s

Multitracker.o: Multitracker.cpp.o
.PHONY : Multitracker.o

# target to build an object file
Multitracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Multitracker.cpp.o
.PHONY : Multitracker.cpp.o

Multitracker.i: Multitracker.cpp.i
.PHONY : Multitracker.i

# target to preprocess a source file
Multitracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Multitracker.cpp.i
.PHONY : Multitracker.cpp.i

Multitracker.s: Multitracker.cpp.s
.PHONY : Multitracker.s

# target to generate assembly for a file
Multitracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Multitracker.cpp.s
.PHONY : Multitracker.cpp.s

SpeedEstimator.o: SpeedEstimator.cpp.o
.PHONY : SpeedEstimator.o

# target to build an object file
SpeedEstimator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/SpeedEstimator.cpp.o
.PHONY : SpeedEstimator.cpp.o

SpeedEstimator.i: SpeedEstimator.cpp.i
.PHONY : SpeedEstimator.i

# target to preprocess a source file
SpeedEstimator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/SpeedEstimator.cpp.i
.PHONY : SpeedEstimator.cpp.i

SpeedEstimator.s: SpeedEstimator.cpp.s
.PHONY : SpeedEstimator.s

# target to generate assembly for a file
SpeedEstimator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/SpeedEstimator.cpp.s
.PHONY : SpeedEstimator.cpp.s

Track.o: Track.cpp.o
.PHONY : Track.o

# target to build an object file
Track.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Track.cpp.o
.PHONY : Track.cpp.o

Track.i: Track.cpp.i
.PHONY : Track.i

# target to preprocess a source file
Track.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Track.cpp.i
.PHONY : Track.cpp.i

Track.s: Track.cpp.s
.PHONY : Track.s

# target to generate assembly for a file
Track.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/Track.cpp.s
.PHONY : Track.cpp.s

detector.o: detector.cpp.o
.PHONY : detector.o

# target to build an object file
detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/detector.cpp.o
.PHONY : detector.cpp.o

detector.i: detector.cpp.i
.PHONY : detector.i

# target to preprocess a source file
detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/detector.cpp.i
.PHONY : detector.cpp.i

detector.s: detector.cpp.s
.PHONY : detector.s

# target to generate assembly for a file
detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/detector.cpp.s
.PHONY : detector.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/main.cpp.s
.PHONY : main.cpp.s

yolo_utils.o: yolo_utils.cpp.o
.PHONY : yolo_utils.o

# target to build an object file
yolo_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/yolo_utils.cpp.o
.PHONY : yolo_utils.cpp.o

yolo_utils.i: yolo_utils.cpp.i
.PHONY : yolo_utils.i

# target to preprocess a source file
yolo_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/yolo_utils.cpp.i
.PHONY : yolo_utils.cpp.i

yolo_utils.s: yolo_utils.cpp.s
.PHONY : yolo_utils.s

# target to generate assembly for a file
yolo_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VA.dir/build.make CMakeFiles/VA.dir/yolo_utils.cpp.s
.PHONY : yolo_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... VA"
	@echo "... Display.o"
	@echo "... Display.i"
	@echo "... Display.s"
	@echo "... HungarianAlg.o"
	@echo "... HungarianAlg.i"
	@echo "... HungarianAlg.s"
	@echo "... Intersection.o"
	@echo "... Intersection.i"
	@echo "... Intersection.s"
	@echo "... Kalman.o"
	@echo "... Kalman.i"
	@echo "... Kalman.s"
	@echo "... MultiCams.o"
	@echo "... MultiCams.i"
	@echo "... MultiCams.s"
	@echo "... Multitracker.o"
	@echo "... Multitracker.i"
	@echo "... Multitracker.s"
	@echo "... SpeedEstimator.o"
	@echo "... SpeedEstimator.i"
	@echo "... SpeedEstimator.s"
	@echo "... Track.o"
	@echo "... Track.i"
	@echo "... Track.s"
	@echo "... detector.o"
	@echo "... detector.i"
	@echo "... detector.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... yolo_utils.o"
	@echo "... yolo_utils.i"
	@echo "... yolo_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

